spring:
  datasource:
    url: jdbc:mysql://localhost:3306/book_borrowing_system?createDatabaseIfNotExist = true
    username: root
    password: 1234



  jpa:
    hibernate:
      ddl-auto: update
    show_sql : true